In [2]:
import numpy as np

In [16]:
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [18]:
x.shape

(5,)

In [20]:
x = np.linspace(0,2,9)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [23]:
x = np.arange(10, 25, 5)
x

array([10, 15, 20])

In [25]:
x = np.full((2,2),7)
x

array([[7, 7],
       [7, 7]])

In [50]:
x = np.random.random((3,3))
x

array([[0.7610499 , 0.12582354, 0.72527656],
       [0.21752593, 0.50528984, 0.01320852],
       [0.91761246, 0.43792884, 0.6486097 ]])

In [55]:
y = np.random.random((3,3))
y

array([[0.32974046, 0.13323609, 0.21549484],
       [0.40263988, 0.17712803, 0.23546582],
       [0.80824799, 0.2446284 , 0.12155181]])

In [57]:
z = x + y
z

array([[1.09079036, 0.25905963, 0.9407714 ],
       [0.6201658 , 0.68241787, 0.24867434],
       [1.72586044, 0.68255725, 0.7701615 ]])

In [60]:
z[0, 1]

0.2590596278613517